name: intl_phone_field
description: A customised Flutter TextFormField to input international phone
  number along with country code.
version: 3.3.1
homepage: https://github.com/vanshg395/intl_phone_field

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.14

dependency_overrides:
  test_api: ^0.7.4

flutter:
  assets:
    - assets/flags/
